spring:
  profiles:
    active: eureka1
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
---
spring:
  profiles: eureka1
  application:
    name: eureka1
eureka:
  instance:
    hostname: eureka1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
server:
  port: 8761
---
spring:
  profiles: eureka2
  application:
    name: eureka2
eureka:
  instance:
    hostname: eureka2
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka3:8763/eureka/
server:
  port: 8762
---
spring:
  profiles: eureka3
  application:
    name: eureka3
eureka:
  instance:
    hostname: eureka3
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
server:
  port: 8763