server:
  servlet:
    context-path: /query/bookings
  port: ${PORT:8082}

spring:
  application:
    name: bookings-service-query
  cloud:
    stream:
      bindings:
        input:
          destination: bookings-events-t
          consumer.headerMode: headers
          group: cargo-location-summary
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092 #146.222.43.12:9092
          headers: event_type,kafka_messageKey