management:
  endpoints:
    web.exposure.include: '*'

eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    non-secure-port: ${server.port:0}


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
#    org.agilehandy.boot.autoconfigure: DEBUG

---
spring:
  profiles: cloud
  cloud:
    services:
      registrationMethod: route
