server:
  servlet:
    context-path: /query/bookings



spring:
  application:
    name: bookings-service-query
  cloud:
    stream:
      bindings:
        input:
          destination: bookings-events
          consumer.headerMode: headers
          group: cargo-location-summary
          content-type: application/json
      kafka:
        binder:
          headers: event_type,kafka_messageKey

eureka:
  client:
    service-url:
      defaultZone: http://discovery1:9661/eureka,http://discovery2:9662/eureka